stages:
  train:
    cmd: python -m src.training
    deps:
    - data/raw/weatherAUS.csv
    - src/data_preparation.py
    - src/training.py
    outs:
    - models/pipeline.joblib
  evaluate:
    cmd: python -m src.evaluation
    deps:
    - data/raw/weatherAUS.csv
    - models/pipeline.joblib
    - src/data_preparation.py
    - src/evaluation.py
    metrics:
    - metrics/eval.json:
        cache: false
  predict:
    cmd: python -m src.predict_batch
    deps:
    - data/raw/weatherAUS.csv
    - models/pipeline.joblib
    - src/predict_batch.py
    outs:
    - outputs/predictions_daily.csv
