FROM apache/airflow:2.10.5

USER airflow
COPY docker/requirements.airflow.extra.txt /tmp/requirements.airflow.extra.txt
RUN pip install --no-cache-dir \
  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.12.txt" \
  -r /tmp/requirements.airflow.extra.txt
