#!/usr/bin/env bash
set -euo pipefail

: "${MLFLOW_TRACKING_URI:?Missing MLFLOW_TRACKING_URI}"
: "${MLFLOW_TRACKING_USERNAME:?Missing MLFLOW_TRACKING_USERNAME}"
: "${MLFLOW_TRACKING_PASSWORD:?Missing MLFLOW_TRACKING_PASSWORD}"
